# Generated by Django 6.0.6 on 2026-07-01 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebHookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
